/**
 * Floating icon configs for service hero visuals.
 */

export const seoFloatingIcons = [
  {
    name: "Google Analytics",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#F15A22",
    textColor: "#fff",
    label: "GA",
    shape: "pill",
  },
  {
    name: "Google Search",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#4285F4",
    textColor: "#fff",
    label: "G",
    shape: "square",
  },
  {
    name: "Keyword Tool",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#10B981",
    textColor: "#fff",
    label: "KW",
    shape: "circle",
  },
  {
    name: "Ahrefs",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#0074D9",
    textColor: "#fff",
    label: "Ah",
    shape: "circle",
  },
  {
    name: "SEMrush",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#FF6B00",
    textColor: "#fff",
    label: "SE",
    shape: "circle",
  },
  {
    name: "Moz",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#FF9900",
    textColor: "#fff",
    label: "Moz",
    shape: "circle",
  },
  {
    name: "Yoast",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#151515",
    textColor: "#fff",
    label: "Yoast",
    shape: "pill-sm",
  },
  {
    name: "Screaming Frog",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#2271B3",
    textColor: "#fff",
    label: "SF",
    shape: "circle",
  },
  {
    name: "Google My Business",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#FFFFFF",
    textColor: "#4285F4",
    label: "GMB",
    shape: "square",
  },
];

export const digitalMarketingFloatingIcons = [
  {
    name: "SEO",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#4285F4",
    textColor: "#fff",
    label: "SEO",
    shape: "pill",
  },
  {
    name: "Social Media",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#E4405F",
    textColor: "#fff",
    label: "SMM",
    shape: "square",
  },
  {
    name: "Ads",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#0A66C2",
    textColor: "#fff",
    label: "Ads",
    shape: "circle",
  },
  {
    name: "Email",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#10B981",
    textColor: "#fff",
    label: "Mail",
    shape: "circle",
  },
  {
    name: "Analytics",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#F15A22",
    textColor: "#fff",
    label: "Data",
    shape: "circle",
  },
  {
    name: "Content",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#FF9900",
    textColor: "#fff",
    label: "Blog",
    shape: "circle",
  },
  {
    name: "PPC",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#fff",
    textColor: "#0A66C2",
    label: "PPC",
    shape: "pill-sm",
  },
  {
    name: "Video",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#FF0000",
    textColor: "#fff",
    label: "YT",
    shape: "circle",
  },
  {
    name: "Influencer",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#C13584",
    textColor: "#fff",
    label: "Inf",
    shape: "square",
  },
];

export const contentWritingFloatingIcons = [
  {
    name: "Copywriting",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#10B981",
    textColor: "#fff",
    label: "Copy",
    shape: "pill",
  },
  {
    name: "Blog Writing",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#3B82F6",
    textColor: "#fff",
    label: "Blog",
    shape: "square",
  },
  {
    name: "SEO Content",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#F59E0B",
    textColor: "#fff",
    label: "SEO",
    shape: "circle",
  },
  {
    name: "Technical Writing",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#8B5CF6",
    textColor: "#fff",
    label: "Tech",
    shape: "circle",
  },
  {
    name: "Creative Writing",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#EC4899",
    textColor: "#fff",
    label: "Creative",
    shape: "circle",
  },
  {
    name: "Editing",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#6366F1",
    textColor: "#fff",
    label: "Edit",
    shape: "circle",
  },
  {
    name: "Proofreading",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#14B8A6",
    textColor: "#fff",
    label: "Proof",
    shape: "pill-sm",
  },
  {
    name: "Ghostwriting",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#F97316",
    textColor: "#fff",
    label: "Ghost",
    shape: "circle",
  },
  {
    name: "Script Writing",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#84CC16",
    textColor: "#fff",
    label: "Script",
    shape: "square",
  },
];

export const appDevelopmentFloatingIcons = [
  {
    name: "React Native",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#61DAFB",
    textColor: "#000",
    label: "RN",
    shape: "pill",
  },
  {
    name: "Flutter",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#02569B",
    textColor: "#fff",
    label: "Fl",
    shape: "square",
  },
  {
    name: "Swift",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#F05133",
    textColor: "#fff",
    label: "Swift",
    shape: "circle",
  },
  {
    name: "Kotlin",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#7F52FF",
    textColor: "#fff",
    label: "Kt",
    shape: "circle",
  },
  {
    name: "Firebase",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#FFCA28",
    textColor: "#000",
    label: "Fb",
    shape: "circle",
  },
  {
    name: "Xcode",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#157EFB",
    textColor: "#fff",
    label: "Xc",
    shape: "circle",
  },
  {
    name: "Android Studio",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#3DDC84",
    textColor: "#000",
    label: "As",
    shape: "pill-sm",
  },
  {
    name: "Ionic",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#3880FF",
    textColor: "#fff",
    label: "Io",
    shape: "circle",
  },
  {
    name: "Dart",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#00B4AB",
    textColor: "#fff",
    label: "Dart",
    shape: "square",
  },
];

export const websiteDevFloatingIcons = [
  {
    name: "Figma",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#1E1E1E",
    textColor: "#F24E1E",
    label: "Figma",
    shape: "pill",
  },
  {
    name: "Adobe XD",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#FF61F6",
    textColor: "#2D001D",
    label: "Xd",
    shape: "square",
  },
  {
    name: "Sketch",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#F7B500",
    textColor: "#fff",
    label: "Sketch",
    shape: "circle",
  },
  {
    name: "Adobe Photoshop",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#001E36",
    textColor: "#31A8FF",
    label: "Ps",
    shape: "circle",
  },
  {
    name: "Adobe Illustrator",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#FF7C00",
    textColor: "#330000",
    label: "Ai",
    shape: "circle",
  },
  {
    name: "InVision",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#FF3366",
    textColor: "#fff",
    label: "Inv",
    shape: "circle",
  },
  {
    name: "Adobe Illustrator",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#326CE5",
    textColor: "#fff",
    label: "Flow",
    shape: "pill-sm",
  },
  {
    name: "Zeplin",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#00C4CC",
    textColor: "#fff",
    label: "Zl",
    shape: "circle",
  },
  {
    name: "Marvel",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#00A859",
    textColor: "#fff",
    label: "Mv",
    shape: "square",
  },
];

export const uiUxFloatingIcons = [
  {
    name: "Figma",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#1E1E1E",
    textColor: "#F24E1E",
    label: "Figma",
    shape: "pill",
  },
  {
    name: "Adobe XD",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#FF61F6",
    textColor: "#2D001D",
    label: "Xd",
    shape: "square",
  },
  {
    name: "Sketch",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#F7B500",
    textColor: "#fff",
    label: "Sketch",
    shape: "circle",
  },
  {
    name: "Adobe Photoshop",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#001E36",
    textColor: "#31A8FF",
    label: "Ps",
    shape: "circle",
  },
  {
    name: "Adobe Illustrator",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#FF7C00",
    textColor: "#330000",
    label: "Ai",
    shape: "circle",
  },
  {
    name: "InVision",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#FF3366",
    textColor: "#fff",
    label: "Inv",
    shape: "circle",
  },
  {
    name: "Adobe Illustrator",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#326CE5",
    textColor: "#fff",
    label: "Flow",
    shape: "pill-sm",
  },
  {
    name: "Zeplin",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#00C4CC",
    textColor: "#fff",
    label: "Zl",
    shape: "circle",
  },
  {
    name: "Marvel",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#00A859",
    textColor: "#fff",
    label: "Mv",
    shape: "square",
  },
];

export const smmFloatingIcons = [
  {
    name: "Facebook",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#1877F2",
    textColor: "#fff",
    label: "FB",
    shape: "pill",
  },
  {
    name: "Instagram",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#E4405F",
    textColor: "#fff",
    label: "IG",
    shape: "square",
  },
  {
    name: "Twitter",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#1DA1F2",
    textColor: "#fff",
    label: "Tw",
    shape: "circle",
  },
  {
    name: "LinkedIn",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#0A66C2",
    textColor: "#fff",
    label: "Li",
    shape: "circle",
  },
  {
    name: "YouTube",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#FF0000",
    textColor: "#fff",
    label: "YT",
    shape: "circle",
  },
  {
    name: "TikTok",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#000000",
    textColor: "#fff",
    label: "TT",
    shape: "circle",
  },
  {
    name: "Pinterest",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#BD081C",
    textColor: "#fff",
    label: "Pi",
    shape: "pill-sm",
  },
  {
    name: "Snapchat",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#FFFC00",
    textColor: "#000",
    label: "Sc",
    shape: "circle",
  },
  {
    name: "Reddit",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#FF4500",
    textColor: "#fff",
    label: "Rd",
    shape: "square",
  },
];

export const graphicDesignFloatingIcons = [
  {
    name: "Adobe Photoshop",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#001E36",
    textColor: "#31A8FF",
    label: "Ps",
    shape: "pill",
  },
  {
    name: "Adobe Illustrator",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#FF7C00",
    textColor: "#330000",
    label: "Ai",
    shape: "square",
  },
  {
    name: "Figma",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#1E1E1E",
    textColor: "#F24E1E",
    label: "Figma",
    shape: "circle",
  },
  {
    name: "Adobe XD",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#FF61F6",
    textColor: "#2D001D",
    label: "Xd",
    shape: "circle",
  },
  {
    name: "Adobe InDesign",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#49021F",
    textColor: "#FF3366",
    label: "Id",
    shape: "circle",
  },
  {
    name: "Canva",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#00C4CC",
    textColor: "#fff",
    label: "Canva",
    shape: "circle",
  },
  {
    name: "Adobe After Effects",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#00005B",
    textColor: "#9999FF",
    label: "Ae",
    shape: "pill-sm",
  },
  {
    name: "Sketch",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#F7B500",
    textColor: "#fff",
    label: "Sketch",
    shape: "circle",
  },
  {
    name: "Blender",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#EA7600",
    textColor: "#fff",
    label: "Blender",
    shape: "square",
  },
];

export const ecommerceFloatingIcons = [
  {
    name: "Shopify",
    delay: 0,
    top: "62%",
    left: "-8%",
    size: 64,
    bg: "#96BF48",
    textColor: "#fff",
    label: "Shop",
    shape: "pill",
  },
  {
    name: "WooCommerce",
    delay: 0.4,
    top: "38%",
    left: "-2%",
    size: 48,
    bg: "#96BF48",
    textColor: "#fff",
    label: "Woo",
    shape: "square",
  },
  {
    name: "Magento",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#F46F21",
    textColor: "#fff",
    label: "Mg",
    shape: "circle",
  },
  {
    name: "Stripe",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#635BFF",
    textColor: "#fff",
    label: "Pi",
    shape: "circle",
  },
  {
    name: "PayPal",
    delay: 1.0,
    top: "18%",
    left: "92%",
    size: 52,
    bg: "#003087",
    textColor: "#fff",
    label: "PP",
    shape: "circle",
  },
  {
    name: "AWS",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#232F3E",
    textColor: "#FF9900",
    label: "AWS",
    shape: "circle",
  },
  {
    name: "Docker",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#2496ED",
    textColor: "#fff",
    label: "Dk",
    shape: "pill-sm",
  },
  {
    name: "Security",
    delay: 0.3,
    top: "16%",
    left: "44%",
    size: 50,
    bg: "#10B981",
    textColor: "#fff",
    label: "SSL",
    shape: "circle",
  },
];

export const itOutsourcingFloatingIcons = [
  {
    name: "Support",
    delay: 0,
    top: "62%",
    left: "-4%",
    size: 56,
    bg: "#0F766E",
    textColor: "#fff",
    label: "Support",
    shape: "pill-sm",
  },
  {
    name: "Remote",
    delay: 0.4,
    top: "26%",
    left: "-2%",
    size: 48,
    bg: "#0EA5E9",
    textColor: "#fff",
    label: "Remote",
    shape: "square",
  },
  {
    name: "Infra",
    delay: 0.8,
    top: "2%",
    left: "30%",
    size: 52,
    bg: "#10B981",
    textColor: "#fff",
    label: "Infra",
    shape: "circle",
  },
  {
    name: "Cloud",
    delay: 0.2,
    top: "4%",
    left: "60%",
    size: 52,
    bg: "#059669",
    textColor: "#fff",
    label: "Cloud",
    shape: "circle",
  },
  {
    name: "Secure",
    delay: 1.0,
    top: "18%",
    left: "92%",
    size: 52,
    bg: "#14B8A6",
    textColor: "#fff",
    label: "Secure",
    shape: "circle",
  },
  {
    name: "Scale",
    delay: 0.6,
    top: "40%",
    left: "96%",
    size: 52,
    bg: "#D97706",
    textColor: "#fff",
    label: "Scale",
    shape: "circle",
  },
  {
    name: "DevOps",
    delay: 1.2,
    top: "62%",
    left: "88%",
    size: 56,
    bg: "#6366F1",
    textColor: "#fff",
    label: "DevOps",
    shape: "pill-sm",
  },
  {
    name: "Cost",
    delay: 0.3,
    top: "16%",
    left: "44%",
    size: 50,
    bg: "#F59E0B",
    textColor: "#fff",
    label: "Save",
    shape: "circle",
  },
];

export const serverManagementFloatingIcons = [
  {
    name: "Setup",
    delay: 0,
    top: "62%",
    left: "-4%",
    size: 56,
    bg: "#0F766E",
    textColor: "#fff",
    label: "Setup",
    shape: "pill-sm",
  },
  {
    name: "Security",
    delay: 0.4,
    top: "26%",
    left: "-2%",
    size: 48,
    bg: "#0EA5E9",
    textColor: "#fff",
    label: "Security",
    shape: "square",
  },
  {
    name: "Monitor",
    delay: 0.8,
    top: "2%",
    left: "30%",
    size: 52,
    bg: "#10B981",
    textColor: "#fff",
    label: "Monitor",
    shape: "circle",
  },
  {
    name: "Cloud",
    delay: 0.2,
    top: "4%",
    left: "60%",
    size: 52,
    bg: "#059669",
    textColor: "#fff",
    label: "Cloud",
    shape: "circle",
  },
  {
    name: "Backup",
    delay: 1.0,
    top: "18%",
    left: "92%",
    size: 52,
    bg: "#14B8A6",
    textColor: "#fff",
    label: "Backup",
    shape: "circle",
  },
  {
    name: "DNS",
    delay: 0.6,
    top: "40%",
    left: "96%",
    size: 52,
    bg: "#D97706",
    textColor: "#fff",
    label: "DNS",
    shape: "circle",
  },
  {
    name: "DB",
    delay: 1.2,
    top: "62%",
    left: "88%",
    size: 56,
    bg: "#fff",
    textColor: "#059669",
    label: "Database",
    shape: "pill-sm",
  },
  {
    name: "Scale",
    delay: 0.3,
    top: "16%",
    left: "44%",
    size: 50,
    bg: "#0D9488",
    textColor: "#fff",
    label: "Scale",
    shape: "circle",
  },
];

export const websiteMaintenanceFloatingIcons = [
  {
    name: "Backup",
    delay: 0,
    top: "62%",
    left: "-4%",
    size: 56,
    bg: "#059669",
    textColor: "#fff",
    label: "Backup",
    shape: "pill-sm",
  },
  {
    name: "Security",
    delay: 0.4,
    top: "26%",
    left: "-2%",
    size: 48,
    bg: "#0EA5E9",
    textColor: "#fff",
    label: "Security",
    shape: "square",
  },
  {
    name: "Speed",
    delay: 0.8,
    top: "2%",
    left: "30%",
    size: 52,
    bg: "#10B981",
    textColor: "#fff",
    label: "Speed",
    shape: "circle",
  },
  {
    name: "SSL",
    delay: 0.2,
    top: "4%",
    left: "60%",
    size: 52,
    bg: "#0F766E",
    textColor: "#fff",
    label: "SSL",
    shape: "circle",
  },
  {
    name: "CDN",
    delay: 1.0,
    top: "18%",
    left: "92%",
    size: 52,
    bg: "#14B8A6",
    textColor: "#fff",
    label: "CDN",
    shape: "circle",
  },
  {
    name: "Uptime",
    delay: 0.6,
    top: "40%",
    left: "96%",
    size: 52,
    bg: "#D97706",
    textColor: "#fff",
    label: "Uptime",
    shape: "circle",
  },
  {
    name: "Updates",
    delay: 1.2,
    top: "62%",
    left: "88%",
    size: 56,
    bg: "#fff",
    textColor: "#059669",
    label: "Updates",
    shape: "pill-sm",
  },
  {
    name: "Monitor",
    delay: 0.3,
    top: "16%",
    left: "44%",
    size: 50,
    bg: "#0D9488",
    textColor: "#fff",
    label: "Monitor",
    shape: "circle",
  },
];

export const systemSoftwareFloatingIcons = [
  {
    name: "Python",
    delay: 0,
    top: "60%",
    left: "-8%",
    size: 64,
    bg: "#306998",
    textColor: "#FFD43B",
    label: "Python",
    shape: "pill",
  },
  {
    name: "C++",
    delay: 0.4,
    top: "36%",
    left: "-2%",
    size: 48,
    bg: "#00599C",
    textColor: "#fff",
    label: "C++",
    shape: "square",
  },
  {
    name: "Rust",
    delay: 0.8,
    top: "2%",
    left: "28%",
    size: 52,
    bg: "#000",
    textColor: "#CE422B",
    label: "Rust",
    shape: "circle",
  },
  {
    name: "Go",
    delay: 0.2,
    top: "4%",
    left: "58%",
    size: 52,
    bg: "#00ACD7",
    textColor: "#fff",
    label: "Go",
    shape: "circle",
  },
  {
    name: "Java",
    delay: 1.0,
    top: "16%",
    left: "92%",
    size: 52,
    bg: "#f89820",
    textColor: "#fff",
    label: "Java",
    shape: "circle",
  },
  {
    name: "Docker",
    delay: 0.6,
    top: "38%",
    left: "96%",
    size: 52,
    bg: "#2496ED",
    textColor: "#fff",
    label: "Docker",
    shape: "circle",
  },
  {
    name: "Kubernetes",
    delay: 1.2,
    top: "58%",
    left: "90%",
    size: 56,
    bg: "#326CE5",
    textColor: "#fff",
    label: "K8s",
    shape: "pill-sm",
  },
  {
    name: "PostgreSQL",
    delay: 0.3,
    top: "14%",
    left: "44%",
    size: 50,
    bg: "#336791",
    textColor: "#fff",
    label: "PgSQL",
    shape: "circle",
  },
  {
    name: "Linux",
    delay: 0.9,
    top: "72%",
    left: "80%",
    size: 48,
    bg: "#1d1d1d",
    textColor: "#f5c518",
    label: "Linux",
    shape: "square",
  },
];
