import Footer from "@/components/layout/Footer";
import RamroGadiBenefitsSection from "@/components/sections/RamroGadiBenefitsSection";
import RamroGadiAboutSection from "@/components/sections/RamroGadiAboutSection";
import Link from "next/link";

const features = [
  {
    title: "Verified Vehicle Listings",
    description:
      "Every listing goes through multi-point inspection verification. Buy with confidence knowing the vehicle history is transparent and accurate.",
  },
  {
    title: "Secure Payments & Escrow",
    description:
      "Protected transaction system with escrow holding. Funds are only released when both buyer and seller confirm the deal is complete.",
  },
  {
    title: "Inspection Reports",
    description:
      "Detailed mechanical, electrical, and cosmetic inspection reports generated by certified mechanics. No hidden surprises after purchase.",
  },
  {
    title: "Integrated Financing",
    description:
      "Compare loan offers from multiple banks and financial institutions directly within the platform. Quick approval in minutes.",
  },
  {
    title: "Smart Search & Filters",
    description:
      "Advanced filtering by brand, price, year, mileage, fuel type, and location. Find your perfect vehicle in seconds, not hours.",
  },
  {
    title: "Document Transfer Assistance",
    description:
      "End-to-end support for ownership transfer, insurance migration, and registration updates. We handle the paperwork so you don't have to.",
  },
];

const stats = [
  { value: "15K+", label: "Verified Listings" },
  { value: "5K+", label: "Happy Customers" },
  { value: "98%", label: "Satisfaction Rate" },
  { value: "500+", label: "Verified Dealers" },
];

export default function RamroGadiPage() {
  return (
    <main>
      <section className="relative bg-navy-950 py-24 md:py-32 overflow-hidden">
        <div
          className="absolute inset-0 opacity-20"
          style={{
            backgroundImage:
              "linear-gradient(180deg, rgba(15, 23, 42, 0.9) 0%, rgba(15, 23, 42, 1) 100%), url('/medimasterhomehero.png')",
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        />
        <div className="max-w-7xl mx-auto px-6 relative z-10">
          <div className="max-w-3xl">
            <span className="inline-block text-teal-400 font-bold text-xs tracking-[0.2em] uppercase mb-4">
              Automotive Marketplace
            </span>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight">
              Buy & Sell Vehicles{" "}
              <span className="text-teal-400">With Confidence</span>
            </h1>
            <p className="text-slate-300 text-lg mb-8 max-w-2xl leading-relaxed">
              Nepal's most trusted automotive marketplace. Buy and sell vehicles
              with secure listings, certified inspection reports, and integrated
              financing tools — all in one platform.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link
                href="/contact"
                className="inline-block px-8 py-4 bg-teal-500 text-white font-bold rounded-xl shadow-glowTeal hover:bg-teal-600 transition-all"
              >
                Get Started
              </Link>
              <Link
                href="/products"
                className="inline-block px-8 py-4 bg-transparent border border-slate-400 text-white font-bold rounded-xl hover:bg-white/10 transition-all"
              >
                Explore Products
              </Link>
            </div>
          </div>
        </div>
      </section>

      <RamroGadiAboutSection />

      <section className="bg-white py-16 border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat) => (
              <div key={stat.label} className="text-center">
                <div
                  className="text-3xl md:text-4xl font-bold text-teal-500 mb-2"
                  style={{ fontFamily: "'Bebas Neue', sans-serif" }}
                >
                  {stat.value}
                </div>
                <div className="text-sm text-slate-500">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <RamroGadiBenefitsSection />

      <Footer />
    </main>
  );
}