import Footer from "@/components/layout/Footer";
import Link from "next/link";

const features = [
  {
    title: "Verified Vehicle Listings",
    description: "Every listing goes through multi-point inspection verification. Buy with confidence knowing the vehicle history is transparent and accurate.",
  },
  {
    title: "Secure Payments & Escrow",
    description: "Protected transaction system with escrow holding. Funds are only released when both buyer and seller confirm the deal is complete.",
  },
  {
    title: "Inspection Reports",
    description: "Detailed mechanical, electrical, and cosmetic inspection reports generated by certified mechanics. No hidden surprises after purchase.",
  },
  {
    title: "Integrated Financing",
    description: "Compare loan offers from multiple banks and financial institutions directly within the platform. Quick approval in minutes.",
  },
  {
    title: "Smart Search & Filters",
    description: "Advanced filtering by brand, price, year, mileage, fuel type, and location. Find your perfect vehicle in seconds, not hours.",
  },
  {
    title: "Document Transfer Assistance",
    description: "End-to-end support for ownership transfer, insurance migration, and registration updates. We handle the paperwork so you don't have to.",
  },
];

const stats = [
  { value: "15K+", label: "Verified Listings" },
  { value: "5K+", label: "Happy Customers" },
  { value: "98%", label: "Satisfaction Rate" },
  { value: "500+", label: "Verified Dealers" },
];

export default function RamroGadiPage() {
  return (
    <main>
      <section className="relative bg-navy-950 py-24 md:py-32 overflow-hidden">
        <div className="absolute inset-0 opacity-20" style={{
          backgroundImage: "linear-gradient(180deg, rgba(15, 23, 42, 0.9) 0%, rgba(15, 23, 42, 1) 100%), url('/medimasterhomehero.png')",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }} />
        <div className="max-w-7xl mx-auto px-6 relative z-10">
          <div className="max-w-3xl">
            <span className="inline-block text-teal-400 font-bold text-xs tracking-[0.2em] uppercase mb-4">
              Automotive Marketplace
            </span>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight">
              Buy & Sell Vehicles <span className="text-teal-400">With Confidence</span>
            </h1>
            <p className="text-slate-300 text-lg mb-8 max-w-2xl leading-relaxed">
              Nepal's most trusted automotive marketplace. Buy and sell vehicles with secure listings, 
              certified inspection reports, and integrated financing tools — all in one platform.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link href="/contact" className="inline-block px-8 py-4 bg-teal-500 text-white font-bold rounded-xl shadow-glowTeal hover:bg-teal-600 transition-all">
                Get Started
              </Link>
              <Link href="/products" className="inline-block px-8 py-4 bg-transparent border border-slate-400 text-white font-bold rounded-xl hover:bg-white/10 transition-all">
                Explore Products
              </Link>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-white py-16 border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat) => (
              <div key={stat.label} className="text-center">
                <div className="text-3xl md:text-4xl font-bold text-teal-500 mb-2" style={{ fontFamily: "'Bebas Neue', sans-serif" }}>
                  {stat.value}
                </div>
                <div className="text-sm text-slate-500">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <span className="text-teal-500 font-bold text-xs tracking-[0.2em] uppercase block mb-3">
              Why Choose Us
            </span>
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
              Your Trusted Vehicle Marketplace
            </h2>
            <p className="text-slate-500 max-w-2xl mx-auto">
              A complete ecosystem for buying and selling vehicles with transparency, security, and convenience at every step.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="bg-white p-8 rounded-2xl border border-slate-100 hover:border-teal-400 hover:shadow-[0_20px_40px_-12px_rgba(0,0,0,0.08)] transition-all duration-300"
              >
                <div className="w-12 h-12 rounded-2xl bg-teal-50 flex items-center justify-center mb-5">
                  <div className="w-3 h-3 rounded-full bg-teal-500" />
                </div>
                <h3 className="text-lg font-bold text-slate-900 mb-3">{feature.title}</h3>
                <p className="text-slate-500 text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 bg-white">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
            Ready to Buy or Sell Your Vehicle?
          </h2>
          <p className="text-slate-500 mb-8 max-w-2xl mx-auto">
            Join thousands of satisfied customers who trust Ramro Gadi for their automotive needs. List your vehicle in minutes.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link href="/contact" className="inline-block px-8 py-4 bg-teal-500 text-white font-bold rounded-xl shadow-glowTeal hover:bg-teal-600 transition-all">
              List Your Vehicle
            </Link>
            <Link href="/services" className="inline-block px-8 py-4 bg-slate-100 text-slate-700 font-bold rounded-xl hover:bg-slate-200 transition-all">
              Our Services
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
