export const CLIENT_STATS = [
  { value: "500+", label: "Active partners" },
  { value: "3", label: "Healthcare sectors" },
  { value: "77", label: "Districts covered" },
  { value: "98%", label: "Client retention" },
];

export const CLIENT_SECTORS = ["All", "Hospitals", "Pharmacies", "Pathology"];

export const CLIENTS = [
  {
    id: 1,
    name: "Grande International Hospital",
    color: "#DC2626",
    bg: "#FEE2E2",
    sector: "Hospitals",
  },
  { id: 2, name: "Nobel Medical College", color: "#2563EB", bg: "#EFF6FF", sector: "Hospitals" },
  {
    id: 3,
    name: "Kathmandu Medical College",
    color: "#059669",
    bg: "#ECFDF5",
    sector: "Hospitals",
  },
  {
    id: 4,
    name: "Manipal Teaching Hospital",
    color: "#7C3AED",
    bg: "#F5F3FF",
    sector: "Hospitals",
  },
  { id: 5, name: "Patan Hospital", color: "#0891B2", bg: "#ECFDF5", sector: "Hospitals" },
  { id: 6, name: "Bir Hospital", color: "#DC2626", bg: "#FEE2E2", sector: "Hospitals" },
  { id: 7, name: "Teku Hospital", color: "#059669", bg: "#ECFDF5", sector: "Hospitals" },
  { id: 8, name: "B&C Medical College", color: "#2563EB", bg: "#EFF6FF", sector: "Hospitals" },
  { id: 9, name: "Devdaha Medical College", color: "#7C3AED", bg: "#F5F3FF", sector: "Hospitals" },
  {
    id: 10,
    name: "Kathmandu Model Hospital",
    color: "#0891B2",
    bg: "#ECFDF5",
    sector: "Hospitals",
  },
  { id: 11, name: "Alka Hospital", color: "#DC2626", bg: "#FEE2E2", sector: "Hospitals" },
  { id: 12, name: "Sumeru Hospital", color: "#059669", bg: "#ECFDF5", sector: "Hospitals" },
  { id: 13, name: "Sagarmatha Hospital", color: "#2563EB", bg: "#EFF6FF", sector: "Hospitals" },
  {
    id: 14,
    name: "Norvic International Hospital",
    color: "#7C3AED",
    bg: "#F5F3FF",
    sector: "Hospitals",
  },
  { id: 15, name: "Ayurveda Hospital", color: "#0891B2", bg: "#ECFDF5", sector: "Hospitals" },
  { id: 16, name: "Shukla Pharmacy", color: "#F59E0B", bg: "#FFFBEB", sector: "Pharmacies" },
  { id: 17, name: "MediCare Pharmacy", color: "#10B981", bg: "#ECFDF5", sector: "Pharmacies" },
  { id: 18, name: "HealthPoint Pharmacy", color: "#8B5CF6", bg: "#FAF5FF", sector: "Pharmacies" },
  { id: 19, name: "Lifeline Pharmacy", color: "#EC4899", bg: "#FCE7F3", sector: "Pharmacies" },
  { id: 20, name: "City Pharmacy", color: "#6366F1", bg: "#E0E7FF", sector: "Pharmacies" },
  { id: 21, name: "Nepal Medical Store", color: "#F59E0B", bg: "#FFFBEB", sector: "Pharmacies" },
  { id: 22, name: "Sajha Pharmacy", color: "#10B981", bg: "#ECFDF5", sector: "Pharmacies" },
  { id: 23, name: "Kantipur Pharmacy", color: "#8B5CF6", bg: "#FAF5FF", sector: "Pharmacies" },
  { id: 24, name: "Guna Pharmacy", color: "#EC4899", bg: "#FCE7F3", sector: "Pharmacies" },
  { id: 25, name: "Siddhi Pharmacy", color: "#6366F1", bg: "#E0E7FF", sector: "Pharmacies" },
  {
    id: 26,
    name: "Everest Diagnostic Center",
    color: "#E11D48",
    bg: "#FFE4E6",
    sector: "Pathology",
  },
  { id: 27, name: "Nepal Pathology Lab", color: "#00A651", bg: "#F0FDF4", sector: "Pathology" },
  {
    id: 28,
    name: "Central Diagnostic Center",
    color: "#0D47A1",
    bg: "#E3F2FD",
    sector: "Pathology",
  },
  { id: 29, name: "Kathmandu Medical Labs", color: "#B91C1C", bg: "#FEE2E2", sector: "Pathology" },
  { id: 30, name: "National Pathology", color: "#1E40AF", bg: "#EFF6FF", sector: "Pathology" },
  { id: 31, name: "Green City Diagnostic", color: "#E11D48", bg: "#FFE4E6", sector: "Pathology" },
  { id: 32, name: "LifeCare Pathology", color: "#00A651", bg: "#F0FDF4", sector: "Pathology" },
  { id: 33, name: "Sagarmatha Diagnostic", color: "#0D47A1", bg: "#E3F2FD", sector: "Pathology" },
  { id: 34, name: "MediPath Laboratory", color: "#B91C1C", bg: "#FEE2E2", sector: "Pathology" },
  { id: 35, name: "Himalayan Pathology", color: "#1E40AF", bg: "#EFF6FF", sector: "Pathology" },
  { id: 36, name: "Dhulikhel Hospital", color: "#0891B2", bg: "#ECFDF5", sector: "Hospitals" },
  {
    id: 37,
    name: "Scheer Memorial Hospital",
    color: "#2563EB",
    bg: "#EFF6FF",
    sector: "Hospitals",
  },
  { id: 38, name: "Lumbini Medical College", color: "#7C3AED", bg: "#F5F3FF", sector: "Hospitals" },
  {
    id: 39,
    name: "Pokhara Academy of Health Sciences",
    color: "#DC2626",
    bg: "#FEE2E2",
    sector: "Hospitals",
  },
  { id: 40, name: "Birat Medical College", color: "#059669", bg: "#ECFDF5", sector: "Hospitals" },
  { id: 41, name: "Janaki Medical College", color: "#0891B2", bg: "#ECFDF5", sector: "Hospitals" },
  {
    id: 42,
    name: "College of Medical Sciences",
    color: "#2563EB",
    bg: "#EFF6FF",
    sector: "Hospitals",
  },
  { id: 43, name: "Om Hospital", color: "#7C3AED", bg: "#F5F3FF", sector: "Hospitals" },
  {
    id: 44,
    name: "Research Institute of Health Science",
    color: "#059669",
    bg: "#ECFDF5",
    sector: "Hospitals",
  },
  { id: 45, name: "Miteri Hospital", color: "#0891B2", bg: "#ECFDF5", sector: "Hospitals" },
  { id: 46, name: "Namaste Pharmacy", color: "#F59E0B", bg: "#FFFBEB", sector: "Pharmacies" },
  { id: 47, name: "Swasthya Pharmacy", color: "#10B981", bg: "#ECFDF5", sector: "Pharmacies" },
  { id: 48, name: "Daily Pharmacy", color: "#8B5CF6", bg: "#FAF5FF", sector: "Pharmacies" },
  { id: 49, name: "Prime Pharmacy", color: "#EC4899", bg: "#FCE7F3", sector: "Pharmacies" },
  { id: 50, name: "Care Pharmacy", color: "#6366F1", bg: "#E0E7FF", sector: "Pharmacies" },
  {
    id: 51,
    name: "Quality Diagnostic Center",
    color: "#E11D48",
    bg: "#FFE4E6",
    sector: "Pathology",
  },
  { id: 52, name: "Shree Diagnostic Lab", color: "#00A651", bg: "#F0FDF4", sector: "Pathology" },
  { id: 53, name: "Metro Pathology", color: "#0D47A1", bg: "#E3F2FD", sector: "Pathology" },
  { id: 54, name: "Ace Laboratory", color: "#B91C1C", bg: "#FEE2E2", sector: "Pathology" },
  { id: 55, name: "Nirmal Pathology", color: "#1E40AF", bg: "#EFF6FF", sector: "Pathology" },
  { id: 56, name: "Divine Diagnostic", color: "#E11D48", bg: "#FFE4E6", sector: "Pathology" },
  { id: 57, name: "WellCare Diagnostic", color: "#00A651", bg: "#F0FDF4", sector: "Pathology" },
  { id: 58, name: "Women's Hospital", color: "#DC2626", bg: "#FEE2E2", sector: "Hospitals" },
  { id: 59, name: "Birgunj Hospital", color: "#059669", bg: "#ECFDF5", sector: "Hospitals" },
  { id: 60, name: "Chitwan Medical College", color: "#2563EB", bg: "#EFF6FF", sector: "Hospitals" },
];

export const MAP_STATS = [
  { value: "150+", label: "Live deployments", hint: "Across Nepal" },
  { value: "77", label: "Districts", hint: "Nationwide coverage" },
  { value: "2M+", label: "Patients managed", hint: "On our platform" },
];
